# Generated by Django 2.0.5 on 2018-06-17 05:16

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_news_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(help_text='Digite o nome da cidade sem abreviações', max_length=255)),
                ('position', geoposition.fields.GeopositionField(help_text='Não altere os valores!!', max_length=42, verbose_name='Geolocalização')),
            ],
        ),
    ]
