# Generated by Django 2.0.5 on 2018-06-17 05:24

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_map'),
    ]

    operations = [
        migrations.DeleteModel(
            name='map',
        ),
        migrations.AddField(
            model_name='news',
            name='cidade',
            field=models.CharField(default=2, help_text='Digite o nome da cidade sem abreviações', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='estado',
            field=models.CharField(default=1, help_text='Digite a sigla do estado', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='position',
            field=geoposition.fields.GeopositionField(default=1, help_text='Não altere os valores!!', max_length=42, verbose_name='Geolocalização'),
            preserve_default=False,
        ),
    ]
