# Generated by Django 2.0.5 on 2018-06-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20180617_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='foto',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
