# Generated by Django 2.0.5 on 2018-06-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_news_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='head',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
