# Generated by Django 2.0.5 on 2018-06-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_news_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='head',
            field=models.TextField(help_text='O Cabeçalho será mostrado apenas no portal!'),
        ),
    ]
