# Generated by Django 2.0.5 on 2018-06-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20180617_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='news',
            name='position',
        ),
        migrations.AddField(
            model_name='news',
            name='legenda',
            field=models.TextField(default=0, help_text='Digite a legenda da foto', max_length=255),
            preserve_default=False,
        ),
    ]
